name = "bhopalimitra"
compatibility_date = "2024-11-01"
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "bhopalimitra_blog"
database_id = "56836796-864b-4f03-ba28-e66d526e4ccf"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BLOG_MEDIA"
bucket_name = "bhopalimitra-blog-media"
