/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogSearchRouteImport } from './routes/blog.search'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ProjectSlugRouteImport } from './routes/project.$slug'
import { Route as ApiBlogCategoriesRouteImport } from './routes/api/blog/categories'
import { Route as ApiBlogPostsRouteImport } from './routes/api/blog/posts'
import { Route as ApiBlogSearchRouteImport } from './routes/api/blog/search'
import { Route as ApiBlogTagsRouteImport } from './routes/api/blog/tags'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.category.$slug'
import { Route as BlogTagSlugRouteImport } from './routes/blog.tag.$slug'
import { Route as AdminAdminBlogIndexRouteImport } from './routes/_admin/admin/blog.index'
import { Route as AdminAdminBlogCategoriesRouteImport } from './routes/_admin/admin/blog.categories'
import { Route as AdminAdminBlogTagsRouteImport } from './routes/_admin/admin/blog.tags'
import { Route as ApiBlogAuthorsSlugRouteImport } from './routes/api/blog/authors.$slug'
import { Route as ApiBlogCategoriesSlugRouteImport } from './routes/api/blog/categories.$slug'
import { Route as ApiBlogPostsSlugRouteImport } from './routes/api/blog/posts.$slug'
import { Route as ApiBlogTagsSlugRouteImport } from './routes/api/blog/tags.$slug'
import { Route as AdminAdminBlogPostsIndexRouteImport } from './routes/_admin/admin/blog.posts.index'
import { Route as AdminAdminBlogPostsNewRouteImport } from './routes/_admin/admin/blog.posts.new'
import { Route as ApiBlogPostsIdIdRouteImport } from './routes/api/blog/posts.id.$id'
import { Route as AdminAdminBlogPostsEditIdRouteImport } from './routes/_admin/admin/blog.posts.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSearchRoute = BlogSearchRouteImport.update({
  id: '/blog/search',
  path: '/blog/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogCategoriesRoute = ApiBlogCategoriesRouteImport.update({
  id: '/api/blog/categories',
  path: '/api/blog/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogPostsRoute = ApiBlogPostsRouteImport.update({
  id: '/api/blog/posts',
  path: '/api/blog/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogSearchRoute = ApiBlogSearchRouteImport.update({
  id: '/api/blog/search',
  path: '/api/blog/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogTagsRoute = ApiBlogTagsRouteImport.update({
  id: '/api/blog/tags',
  path: '/api/blog/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/category/$slug',
  path: '/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagSlugRoute = BlogTagSlugRouteImport.update({
  id: '/blog/tag/$slug',
  path: '/blog/tag/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminBlogIndexRoute = AdminAdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBlogCategoriesRoute =
  AdminAdminBlogCategoriesRouteImport.update({
    id: '/admin/blog/categories',
    path: '/admin/blog/categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminBlogTagsRoute = AdminAdminBlogTagsRouteImport.update({
  id: '/admin/blog/tags',
  path: '/admin/blog/tags',
  getParentRoute: () => AdminRoute,
} as any)
const ApiBlogAuthorsSlugRoute = ApiBlogAuthorsSlugRouteImport.update({
  id: '/api/blog/authors/$slug',
  path: '/api/blog/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogCategoriesSlugRoute = ApiBlogCategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBlogCategoriesRoute,
} as any)
const ApiBlogPostsSlugRoute = ApiBlogPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBlogPostsRoute,
} as any)
const ApiBlogTagsSlugRoute = ApiBlogTagsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBlogTagsRoute,
} as any)
const AdminAdminBlogPostsIndexRoute =
  AdminAdminBlogPostsIndexRouteImport.update({
    id: '/admin/blog/posts/',
    path: '/admin/blog/posts/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminBlogPostsNewRoute = AdminAdminBlogPostsNewRouteImport.update({
  id: '/admin/blog/posts/new',
  path: '/admin/blog/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiBlogPostsIdIdRoute = ApiBlogPostsIdIdRouteImport.update({
  id: '/id/$id',
  path: '/id/$id',
  getParentRoute: () => ApiBlogPostsRoute,
} as any)
const AdminAdminBlogPostsEditIdRoute =
  AdminAdminBlogPostsEditIdRouteImport.update({
    id: '/admin/blog/posts/edit/$id',
    path: '/admin/blog/posts/edit/$id',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/blog/categories': typeof ApiBlogCategoriesRouteWithChildren
  '/api/blog/posts': typeof ApiBlogPostsRouteWithChildren
  '/api/blog/search': typeof ApiBlogSearchRoute
  '/api/blog/tags': typeof ApiBlogTagsRouteWithChildren
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog/categories': typeof AdminAdminBlogCategoriesRoute
  '/admin/blog/tags': typeof AdminAdminBlogTagsRoute
  '/api/blog/authors/$slug': typeof ApiBlogAuthorsSlugRoute
  '/api/blog/categories/$slug': typeof ApiBlogCategoriesSlugRoute
  '/api/blog/posts/$slug': typeof ApiBlogPostsSlugRoute
  '/api/blog/tags/$slug': typeof ApiBlogTagsSlugRoute
  '/admin/blog/': typeof AdminAdminBlogIndexRoute
  '/admin/blog/posts/new': typeof AdminAdminBlogPostsNewRoute
  '/api/blog/posts/id/$id': typeof ApiBlogPostsIdIdRoute
  '/admin/blog/posts/': typeof AdminAdminBlogPostsIndexRoute
  '/admin/blog/posts/edit/$id': typeof AdminAdminBlogPostsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/blog': typeof BlogIndexRoute
  '/api/blog/categories': typeof ApiBlogCategoriesRouteWithChildren
  '/api/blog/posts': typeof ApiBlogPostsRouteWithChildren
  '/api/blog/search': typeof ApiBlogSearchRoute
  '/api/blog/tags': typeof ApiBlogTagsRouteWithChildren
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/admin/blog/categories': typeof AdminAdminBlogCategoriesRoute
  '/admin/blog/tags': typeof AdminAdminBlogTagsRoute
  '/api/blog/authors/$slug': typeof ApiBlogAuthorsSlugRoute
  '/api/blog/categories/$slug': typeof ApiBlogCategoriesSlugRoute
  '/api/blog/posts/$slug': typeof ApiBlogPostsSlugRoute
  '/api/blog/tags/$slug': typeof ApiBlogTagsSlugRoute
  '/admin/blog': typeof AdminAdminBlogIndexRoute
  '/admin/blog/posts/new': typeof AdminAdminBlogPostsNewRoute
  '/api/blog/posts/id/$id': typeof ApiBlogPostsIdIdRoute
  '/admin/blog/posts': typeof AdminAdminBlogPostsIndexRoute
  '/admin/blog/posts/edit/$id': typeof AdminAdminBlogPostsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/projects': typeof ProjectsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/trending': typeof TrendingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/project/$slug': typeof ProjectSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/api/blog/categories': typeof ApiBlogCategoriesRouteWithChildren
  '/api/blog/posts': typeof ApiBlogPostsRouteWithChildren
  '/api/blog/search': typeof ApiBlogSearchRoute
  '/api/blog/tags': typeof ApiBlogTagsRouteWithChildren
  '/blog/category/$slug': typeof BlogCategorySlugRoute
  '/blog/tag/$slug': typeof BlogTagSlugRoute
  '/_admin/admin/blog/categories': typeof AdminAdminBlogCategoriesRoute
  '/_admin/admin/blog/tags': typeof AdminAdminBlogTagsRoute
  '/api/blog/authors/$slug': typeof ApiBlogAuthorsSlugRoute
  '/api/blog/categories/$slug': typeof ApiBlogCategoriesSlugRoute
  '/api/blog/posts/$slug': typeof ApiBlogPostsSlugRoute
  '/api/blog/tags/$slug': typeof ApiBlogTagsSlugRoute
  '/_admin/admin/blog/': typeof AdminAdminBlogIndexRoute
  '/_admin/admin/blog/posts/new': typeof AdminAdminBlogPostsNewRoute
  '/api/blog/posts/id/$id': typeof ApiBlogPostsIdIdRoute
  '/_admin/admin/blog/posts/': typeof AdminAdminBlogPostsIndexRoute
  '/_admin/admin/blog/posts/edit/$id': typeof AdminAdminBlogPostsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/projects'
    | '/refund-policy'
    | '/terms'
    | '/trending'
    | '/blog/$slug'
    | '/blog/search'
    | '/category/$slug'
    | '/project/$slug'
    | '/blog/'
    | '/api/blog/categories'
    | '/api/blog/posts'
    | '/api/blog/search'
    | '/api/blog/tags'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog/categories'
    | '/admin/blog/tags'
    | '/api/blog/authors/$slug'
    | '/api/blog/categories/$slug'
    | '/api/blog/posts/$slug'
    | '/api/blog/tags/$slug'
    | '/admin/blog/'
    | '/admin/blog/posts/new'
    | '/api/blog/posts/id/$id'
    | '/admin/blog/posts/'
    | '/admin/blog/posts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/projects'
    | '/refund-policy'
    | '/terms'
    | '/trending'
    | '/blog/$slug'
    | '/blog/search'
    | '/category/$slug'
    | '/project/$slug'
    | '/blog'
    | '/api/blog/categories'
    | '/api/blog/posts'
    | '/api/blog/search'
    | '/api/blog/tags'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/admin/blog/categories'
    | '/admin/blog/tags'
    | '/api/blog/authors/$slug'
    | '/api/blog/categories/$slug'
    | '/api/blog/posts/$slug'
    | '/api/blog/tags/$slug'
    | '/admin/blog'
    | '/admin/blog/posts/new'
    | '/api/blog/posts/id/$id'
    | '/admin/blog/posts'
    | '/admin/blog/posts/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/projects'
    | '/refund-policy'
    | '/terms'
    | '/trending'
    | '/blog/$slug'
    | '/blog/search'
    | '/category/$slug'
    | '/project/$slug'
    | '/blog/'
    | '/api/blog/categories'
    | '/api/blog/posts'
    | '/api/blog/search'
    | '/api/blog/tags'
    | '/blog/category/$slug'
    | '/blog/tag/$slug'
    | '/_admin/admin/blog/categories'
    | '/_admin/admin/blog/tags'
    | '/api/blog/authors/$slug'
    | '/api/blog/categories/$slug'
    | '/api/blog/posts/$slug'
    | '/api/blog/tags/$slug'
    | '/_admin/admin/blog/'
    | '/_admin/admin/blog/posts/new'
    | '/api/blog/posts/id/$id'
    | '/_admin/admin/blog/posts/'
    | '/_admin/admin/blog/posts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProjectsRoute: typeof ProjectsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  TrendingRoute: typeof TrendingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogSearchRoute: typeof BlogSearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProjectSlugRoute: typeof ProjectSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiBlogCategoriesRoute: typeof ApiBlogCategoriesRouteWithChildren
  ApiBlogPostsRoute: typeof ApiBlogPostsRouteWithChildren
  ApiBlogSearchRoute: typeof ApiBlogSearchRoute
  ApiBlogTagsRoute: typeof ApiBlogTagsRouteWithChildren
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogTagSlugRoute: typeof BlogTagSlugRoute
  ApiBlogAuthorsSlugRoute: typeof ApiBlogAuthorsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/search': {
      id: '/blog/search'
      path: '/blog/search'
      fullPath: '/blog/search'
      preLoaderRoute: typeof BlogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/categories': {
      id: '/api/blog/categories'
      path: '/api/blog/categories'
      fullPath: '/api/blog/categories'
      preLoaderRoute: typeof ApiBlogCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/posts': {
      id: '/api/blog/posts'
      path: '/api/blog/posts'
      fullPath: '/api/blog/posts'
      preLoaderRoute: typeof ApiBlogPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/search': {
      id: '/api/blog/search'
      path: '/api/blog/search'
      fullPath: '/api/blog/search'
      preLoaderRoute: typeof ApiBlogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/tags': {
      id: '/api/blog/tags'
      path: '/api/blog/tags'
      fullPath: '/api/blog/tags'
      preLoaderRoute: typeof ApiBlogTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$slug': {
      id: '/blog/category/$slug'
      path: '/blog/category/$slug'
      fullPath: '/blog/category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$slug': {
      id: '/blog/tag/$slug'
      path: '/blog/tag/$slug'
      fullPath: '/blog/tag/$slug'
      preLoaderRoute: typeof BlogTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/blog/': {
      id: '/_admin/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminAdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blog/categories': {
      id: '/_admin/admin/blog/categories'
      path: '/admin/blog/categories'
      fullPath: '/admin/blog/categories'
      preLoaderRoute: typeof AdminAdminBlogCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blog/tags': {
      id: '/_admin/admin/blog/tags'
      path: '/admin/blog/tags'
      fullPath: '/admin/blog/tags'
      preLoaderRoute: typeof AdminAdminBlogTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/blog/authors/$slug': {
      id: '/api/blog/authors/$slug'
      path: '/api/blog/authors/$slug'
      fullPath: '/api/blog/authors/$slug'
      preLoaderRoute: typeof ApiBlogAuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/categories/$slug': {
      id: '/api/blog/categories/$slug'
      path: '/$slug'
      fullPath: '/api/blog/categories/$slug'
      preLoaderRoute: typeof ApiBlogCategoriesSlugRouteImport
      parentRoute: typeof ApiBlogCategoriesRoute
    }
    '/api/blog/posts/$slug': {
      id: '/api/blog/posts/$slug'
      path: '/$slug'
      fullPath: '/api/blog/posts/$slug'
      preLoaderRoute: typeof ApiBlogPostsSlugRouteImport
      parentRoute: typeof ApiBlogPostsRoute
    }
    '/api/blog/tags/$slug': {
      id: '/api/blog/tags/$slug'
      path: '/$slug'
      fullPath: '/api/blog/tags/$slug'
      preLoaderRoute: typeof ApiBlogTagsSlugRouteImport
      parentRoute: typeof ApiBlogTagsRoute
    }
    '/_admin/admin/blog/posts/': {
      id: '/_admin/admin/blog/posts/'
      path: '/admin/blog/posts'
      fullPath: '/admin/blog/posts/'
      preLoaderRoute: typeof AdminAdminBlogPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blog/posts/new': {
      id: '/_admin/admin/blog/posts/new'
      path: '/admin/blog/posts/new'
      fullPath: '/admin/blog/posts/new'
      preLoaderRoute: typeof AdminAdminBlogPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/blog/posts/id/$id': {
      id: '/api/blog/posts/id/$id'
      path: '/id/$id'
      fullPath: '/api/blog/posts/id/$id'
      preLoaderRoute: typeof ApiBlogPostsIdIdRouteImport
      parentRoute: typeof ApiBlogPostsRoute
    }
    '/_admin/admin/blog/posts/edit/$id': {
      id: '/_admin/admin/blog/posts/edit/$id'
      path: '/admin/blog/posts/edit/$id'
      fullPath: '/admin/blog/posts/edit/$id'
      preLoaderRoute: typeof AdminAdminBlogPostsEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminBlogCategoriesRoute: typeof AdminAdminBlogCategoriesRoute
  AdminAdminBlogTagsRoute: typeof AdminAdminBlogTagsRoute
  AdminAdminBlogIndexRoute: typeof AdminAdminBlogIndexRoute
  AdminAdminBlogPostsNewRoute: typeof AdminAdminBlogPostsNewRoute
  AdminAdminBlogPostsIndexRoute: typeof AdminAdminBlogPostsIndexRoute
  AdminAdminBlogPostsEditIdRoute: typeof AdminAdminBlogPostsEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminBlogCategoriesRoute: AdminAdminBlogCategoriesRoute,
  AdminAdminBlogTagsRoute: AdminAdminBlogTagsRoute,
  AdminAdminBlogIndexRoute: AdminAdminBlogIndexRoute,
  AdminAdminBlogPostsNewRoute: AdminAdminBlogPostsNewRoute,
  AdminAdminBlogPostsIndexRoute: AdminAdminBlogPostsIndexRoute,
  AdminAdminBlogPostsEditIdRoute: AdminAdminBlogPostsEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiBlogCategoriesRouteChildren {
  ApiBlogCategoriesSlugRoute: typeof ApiBlogCategoriesSlugRoute
}

const ApiBlogCategoriesRouteChildren: ApiBlogCategoriesRouteChildren = {
  ApiBlogCategoriesSlugRoute: ApiBlogCategoriesSlugRoute,
}

const ApiBlogCategoriesRouteWithChildren =
  ApiBlogCategoriesRoute._addFileChildren(ApiBlogCategoriesRouteChildren)

interface ApiBlogPostsRouteChildren {
  ApiBlogPostsSlugRoute: typeof ApiBlogPostsSlugRoute
  ApiBlogPostsIdIdRoute: typeof ApiBlogPostsIdIdRoute
}

const ApiBlogPostsRouteChildren: ApiBlogPostsRouteChildren = {
  ApiBlogPostsSlugRoute: ApiBlogPostsSlugRoute,
  ApiBlogPostsIdIdRoute: ApiBlogPostsIdIdRoute,
}

const ApiBlogPostsRouteWithChildren = ApiBlogPostsRoute._addFileChildren(
  ApiBlogPostsRouteChildren,
)

interface ApiBlogTagsRouteChildren {
  ApiBlogTagsSlugRoute: typeof ApiBlogTagsSlugRoute
}

const ApiBlogTagsRouteChildren: ApiBlogTagsRouteChildren = {
  ApiBlogTagsSlugRoute: ApiBlogTagsSlugRoute,
}

const ApiBlogTagsRouteWithChildren = ApiBlogTagsRoute._addFileChildren(
  ApiBlogTagsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProjectsRoute: ProjectsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  TrendingRoute: TrendingRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogSearchRoute: BlogSearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProjectSlugRoute: ProjectSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiBlogCategoriesRoute: ApiBlogCategoriesRouteWithChildren,
  ApiBlogPostsRoute: ApiBlogPostsRouteWithChildren,
  ApiBlogSearchRoute: ApiBlogSearchRoute,
  ApiBlogTagsRoute: ApiBlogTagsRouteWithChildren,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogTagSlugRoute: BlogTagSlugRoute,
  ApiBlogAuthorsSlugRoute: ApiBlogAuthorsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
